version: '3.4'

services:
  supervisor:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: supervisord
    container_name: supervisor
    volumes:
      - ./src:/app
      - ./logs/supervisord:/var/log
    links:
      - postgres
    depends_on:
      - migration
      - postgres
  php:
    build:
      context: .docker
      target: base
    working_dir: /app
    volumes:
      - ./src:/app
    links:
      - postgres
    depends_on:
      - migration
      - postgres
    entrypoint: ["php"]
  migration:
    build:
      context: .docker
      target: base
    working_dir: /app/migration
    volumes:
      - ./src/log:/app/log
      - ./src/db:/app/db
      - ./src/migration:/app/migration
    links:
      - postgres
    depends_on:
      - postgres
    entrypoint: ["sh", "-c", "php init-db.php && php fixtures.php"]
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'