version: '3.4'

services:
  tests:
    build:
      context: .docker
      target: base
    working_dir: /app
    volumes:
      - ./src:/app
    links:
      - postgres-test
    depends_on:
      migration-test:
        condition: service_completed_successfully
      postgres-test:
        condition: service_healthy
    entrypoint: ["php", "./tests/functional/run.php"]
    environment:
      DB: tests
      DB_HOST: postgres-test
    networks:
      - tests
  migration-test:
    build:
      context: .docker
      target: base
    working_dir: /app/migration
    volumes:
      - ./src/log:/app/log
      - ./src/db:/app/db
      - ./src/migration:/app/migration
    links:
      - postgres-test
    depends_on:
      postgres-test:
        condition: service_healthy
    entrypoint: ["sh", "-c", "php init-db.php"]
    environment:
      DB: tests
      DB_HOST: postgres-test
    networks:
      - tests
  postgres-test:
    image: postgres
    environment:
      POSTGRES_DB: tests
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - '5433:5432'
    networks:
      - tests
networks:
  tests: